### ISSUE TITLE
[wiki] 課題解決メモ

### ISSUE THREAD

**Issue by takahiromasui001** [takahiromasui001/certain-sample#53]
# certain-sample 課題解決メモ
## CORSはひとまず以下で解決
https://note.com/artefactnote/n/n6f84e9585f95#lPwG9

## ant-designとmomentに関して
https://twitter.com/kpinput/status/1256801575005118465

# 設計方針メモ
## URL設計に関して
jira_cloneを真似る。普通にリソースとidをネストする感じ
https://github.com/oldboyxx/jira_clone

## 仕様書の各項目における特殊事例への対応
- 特定の項目だけ、カラーが2つあるといったケースが存在する
- 特定の項目に対して、新規にテーブルを作成することで対応。
  - 例えば既製建具には建具と敷居の2つのカラー設定があるが、これは専用のテーブルを作成することで対応する。
  - 他にも似たケースがある場合は同様の対応とする

## カスタマイズ要望に関して
- まずプロダクトに対してなんらかの分類を用いる必要があるかもしれない。
- カスタマイズグループを作成する
- もしくはカスタマイズ候補として繋げるとか。
- ツリー構造のcandidate_item & candidate_colorを作るとか？

## 仕様書のモデル構造に関して
- 仕様 & 仕様書アイテム(その他すべて)の構成でいいのでは？という気がしてきた。
  案外妙案では？
  - 内部仕様書、外部仕様書等の構成は、仕様書アイテムにtypeとして持たせる

# 懸念点メモ
- Productには、仕様書毎に個数の設定ができる必要がありそう。どういうデータ構造にする。。。？
  -> SpecificationItem側に持たせる感じでどうだろうか
- Productにpriceはなくていいのでは？
  -> specification側にpriceを持たせる(保留)
  -> Product側は単価、specification_item側は別

# todo
- [x] 作成や編集はモーダルにしたい
- [ ] apiのパラメータ名をsnake_case/calmeCaseのどちらに合わせる？またその合わせ方は？
- [ ] ディレクトリ構造は検討の余地があるかも？
- [ ] specification_itemsにcustomize = true/falseをつけたほうが良さそう。さらにupdated_byも欲しいか。。。？
- [ ] 仕様書リストは、React DnDで並び替えられるようにしたいな。。。
- [ ] productにどの仕様書タイプで利用するかの情報を追加する？
- [ ] 仕様書タイプもテーブル作ったほうが良いか？さらにフロントではAPIで取得する形が良いか？？？
- [ ] 型のanyは潰したい
